In [ ]:
# Example 1: numpy.array()

In [1]:
import numpy as np  
arr=np.array([1,2,3])  
print(arr) 

[1 2 3]


In [ ]:
# Example 2: Elements of different type

In [2]:
import numpy as np  
arr=np.array([1,2.,3.])  
print(arr)

[1. 2. 3.]


In [ ]:
# Example 3: More than one dimensions - double square brackets indicates a 2D array

In [4]:
import numpy as np
arr=np.array([[1.,2.,3.],[3.,4.,5.]])
print(arr)

[[1. 2. 3.]
 [3. 4. 5.]]


In [ ]:
# Example 4: Minimum dimensions: 2

In [9]:
import numpy as np
arr=np.array([1,2.,3.],ndmin=2)
print(arr)

[[1. 2. 3.]]


In [ ]:
# Example 5: Type provided: Elements to be shown inn the form of complex numbers

In [13]:
import numpy as np
arr=np.array([12,32.,2],dtype=complex)
print(arr)

[12.+0.j 32.+0.j  2.+0.j]


In [ ]:
# Example 6: Creating an array from sub-classes

In [19]:
import numpy as np
arr=np.array(np.mat('1,2;3,4'))
print(arr)
print("-----------")
arr=np.array(np.mat('1,2;3,4'),subok=True)
print(arr)

[[1 2]
 [3 4]]
-----------
[[1 2]
 [3 4]]
